name: Deploy the main branch
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Build
        run: |
          npm ci
          npm run build:prod

      - name: Deploy
        uses: actions/checkout@v2
        uses: lowply/deploy-firebase@v0.0.5
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
